### ISSUE TITLE
Item Cron ItemUpdate: Notice: Undefined index: id

### ISSUE THREAD

**Issue by jorgb90** [magmodules/magento2-channable#154] opened 2022-04-20 14:25 UTC
[2022-04-20 14:20:06] Channable.INFO: Item Cron ItemUpdate: Notice: Undefined index: id in /home/xxxxxx/public_html/vendor/magmodules/magento2-channable/Model/Item.php on line 435 [] []

**Comment by Frank-Magmodules** [comment] 2022-04-25 17:30
Hi @jorgb90,

Thank you for opening this issue. As we can't reproduce this issue, please share the staging/development details of this store using our [contact form](https://www.magmodules.eu/support-form.html) together with the exact steps on how we can reproduce the issue so we can further debug this issue.

**Comment by Stoux** [comment] 2022-04-26 10:13
We're experiencing the same issue.  Here's a Sentry dump that might be useful:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/4819194/165275237-0c784602-e627-4ef3-b5ac-8dea26eee97e.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/4819194/165277763-d45b37b0-d063-49e7-a818-800473f5b8c4.png">

**Comment by Frank-Magmodules** [comment] 2022-04-29 12:24
HI @jorgb90 and @Stoux ,

I'm happy to share that Channable fixed this issue and that I've just tested this as working again.
We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2022-04-29 12:24 UTC
