### ISSUE TITLE
price_config not defined in $config when called in processPrice

### ISSUE THREAD

**Issue by rensieeee** [magmodules/magento2-channable#128] opened 2021-09-17 14:28 UTC
In `\Magmodules\Channable\Helper\Product`, when calling processPrice, the $config variable does not contain the ['price_config] key anymore. This did exist in 1.5.2.

As a result, all isset() calls on values inside it return false, so any exchange rates/configuration is ignored.

**Comment by Marvin-Magmodules** [comment] 2021-09-17 15:08
Hi @rensieeee what version are you running at this moment?

**Comment by rensieeee** [comment] 2021-09-20 07:28
Hi @Marvin-Magmodules ,

I just upgraded from dev-fix/price-processor to 1.5.4.

**Comment by Marvin-Magmodules** [comment] 2021-09-20 13:15
Hi @rensieeee,

Seems we can't reproduce this issue from our side, can you please fill in our [support form](https://www.magmodules.eu/support-form.html) with (preferably staging/development) details of the environment so we can take a look with you on this issue?

**Comment by Frank-Magmodules** [comment] 2022-07-19 12:45
Hi @rensieeee ,

Due to the lack of information and the fact that we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-07-19 12:45 UTC
