### ISSUE TITLE
Notice: Array to string conversion in vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170

### ISSUE THREAD

**Issue by batmike** [magmodules/magento2-channable#118] opened 2021-08-13 13:47 UTC
In working with Magento's version 2.4.3, when sending an order from the Channable system to Magento, I'm getting the following error:

Channable.INFO: importOrder: xxxxxxxx: Notice: Array to string conversion in vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170

At that point, the order fails to import. If there's anything I can test out or try for a quick fix, let me know.

Thanks!

**Comment by Frank-Magmodules** [comment] 2021-08-16 14:07
Hi @batmike, thank you for opening this issue. 
We are looking into this issue at this moment and will try to release a fix asap.
Thank you for your patience here.

**Comment by Frank-Magmodules** [comment] 2021-08-17 08:41
Hi @batmike, 

We have created a hotfix for this issue, as we need some more time to check the root cause of this issue. 
Looks like setting the street lines as array for the customer address has changed in 2.4.3. 

Can you validate if this [branch](https://github.com/magmodules/magento2-channable/commits/hotfix/243-compatibility) also fixes the issue on your side?
This fix has also been tested internally.

Thank you for your cooperation!

**Comment by batmike** [comment] 2021-08-17 15:10
@Frank-Magmodules -

Thanks for the hotfix and I deployed that and pushed over our recent Amazon orders that were previously triggering these errors. They came across without issue so this fix worked well.

**Comment by Frank-Magmodules** [comment] 2021-08-17 19:17
Hi @batmike ,

Great! We are happy to share that we've just released the new [1.5.2](https://github.com/magmodules/magento2-channable/releases/tag/1.5.2) version with this fix. Thank you for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2021-08-17 19:17 UTC
