### ISSUE TITLE
Compatibility issue with Amasty Shop By module

### ISSUE THREAD

**Issue by rjm87** [magmodules/magento2-channable#150] opened 2022-04-08 07:08 UTC
There seems to be a compatibility issue with the latest version of the Amasty Shop By module (v1.18.4). The issue breaks all the direct links to filter pages; f.e. domain.com/filter/brandname, resulting in a lot of 404 not found pages.

I've reached out to Amasty and they have replied with the following;

To resolve this issue, a following file was changed:
vendor/magmodules/magento2-channable/Plugin/AroundIsAllowedRequest.php
And here's the link to download the changed file: [357024.97.zip](https://github.com/magmodules/magento2-channable/files/8449390/357024.97.zip)

Could you check if can be fixed from your side? If you need more information, please let me know.

**Comment by arko-betersport** [comment] 2022-04-08 10:29
Just discovered the same problem. All filter pages are returning HTTP 404 after this update.

**Comment by Marvin-Magmodules** [comment] 2022-04-10 18:18
@rjm87, @arko-betersport, thank you for opening this issue. We are trying to reproduce this issue on our channable development environment, but are not able to break it. All brand pages still work as intended, but could be we are using different settings. Is there a staging/dev env available to check this issue? If yes, can you contact us though: https://www.magmodules.eu/support-form.html

Other option would be we share out dev env to double check if this is related to our settings.

**Comment by rjm87** [comment] 2022-04-11 07:55
I've sent you the staging env. of our client. Please let me know if you can
reproduce the issue there.

Rolf

**Comment by Frank-Magmodules** [comment] 2022-04-11 11:56
Hi @rjm87  and @arko-betersport ,

We are happy to share that we've just released the new [1.8.1](https://github.com/magmodules/magento2-channable/releases/tag/1.8.1) version where we have fixed this issue. Thank you for opening this issue and sharing the detailed issue report through our contact form, which helped us to reproduce the issue on our end.

We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2022-04-11 11:56 UTC
